/* ===================================================================
   ترندات تيك توك · السعودية — app.js
   Static, dependency-free. Renders a physics "swarm" of trending
   hashtags on <canvas>, plus a filterable list view.
   Data comes from window.TREND_DATA (generated by scripts/build-data.mjs).
   =================================================================== */
(function () {
  "use strict";

  var DATA = window.TREND_DATA;
  if (!DATA) {
    document.body.insertAdjacentHTML(
      "beforeend",
      '<p style="padding:40px;color:#fff">تعذّر تحميل البيانات (data.js).</p>'
    );
    return;
  }

  var CATS = DATA.categories;
  var ITEMS = DATA.items;

  // ---- state ----
  var state = {
    view: "swarm",
    search: "",
    activeCats: new Set(Object.keys(CATS)), // all on
    ksaOnly: false,
  };

  // ---- helpers ----
  var $ = function (sel) { return document.querySelector(sel); };
  var catColor = function (key) { return (CATS[key] || CATS.other).color; };
  var catName = function (key) { return (CATS[key] || CATS.other).ar; };
  var catIcon = function (key) { return (CATS[key] || CATS.other).icon; };

  function matches(item) {
    if (!state.activeCats.has(item.category)) return false;
    if (state.ksaOnly && !item.ksa) return false;
    if (state.search) {
      var q = state.search.toLowerCase();
      if (item.tag.toLowerCase().indexOf(q) === -1) return false;
    }
    return true;
  }

  function fmtDate(iso) {
    try {
      return new Intl.DateTimeFormat("ar", {
        day: "numeric", month: "long", year: "numeric", calendar: "gregory",
      }).format(new Date(iso));
    } catch (e) {
      return (iso || "").slice(0, 10);
    }
  }

  // =================================================================
  // Header meta + footer
  // =================================================================
  $("#asOfChip").textContent = "آخر تحديث: " + fmtDate(DATA.meta.as_of);
  $("#countChip").textContent = DATA.meta.count + " هاشتاق";
  $("#sourceNote").textContent = "المصدر: " + DATA.meta.source + " — " + DATA.meta.note_ar;

  // =================================================================
  // Legend
  // =================================================================
  var legendEl = $("#legend");
  function buildLegend() {
    legendEl.innerHTML = "";
    DATA.breakdown.forEach(function (c) {
      var chip = document.createElement("button");
      chip.className = "cat-chip";
      chip.dataset.cat = c.key;
      chip.innerHTML =
        '<span class="dot" style="background:' + c.color + '"></span>' +
        "<span>" + c.icon + " " + c.ar + "</span>" +
        '<span class="cat-count">' + c.count + "</span>";
      chip.addEventListener("click", function () {
        if (state.activeCats.has(c.key)) state.activeCats.delete(c.key);
        else state.activeCats.add(c.key);
        chip.classList.toggle("is-off", !state.activeCats.has(c.key));
        applyFilters();
      });
      legendEl.appendChild(chip);
    });
  }

  // =================================================================
  // Stats
  // =================================================================
  var statsEl = $("#stats");
  function renderStats() {
    var visible = ITEMS.filter(matches);
    var top = DATA.breakdown[0];
    var ksaCount = ITEMS.filter(function (i) { return i.ksa; }).length;
    statsEl.innerHTML =
      statCard(visible.length, "/ " + DATA.meta.count, "هاشتاق ظاهر", true) +
      statCard(DATA.breakdown.length, "", "فئة مختلفة", false) +
      statCard(top.icon + " " + top.ar, "", "الأكثر رواجاً (" + top.count + ")", false) +
      statCard("★ " + ksaCount, "", "أبرز للسعودية", false);
  }
  function statCard(val, unit, label, accent) {
    return (
      '<div class="stat-card">' +
      '<div class="stat-val ' + (accent ? "accent" : "") + '">' +
      val + (unit ? ' <span class="unit">' + unit + "</span>" : "") +
      "</div>" +
      '<div class="stat-label">' + label + "</div></div>"
    );
  }

  // =================================================================
  // List view
  // =================================================================
  var listGrid = $("#listGrid");
  var listEmpty = $("#listEmpty");
  function renderList() {
    var visible = ITEMS.filter(matches).sort(function (a, b) { return a.rank - b.rank; });
    listEmpty.hidden = visible.length > 0;
    listGrid.innerHTML = visible.map(function (it) {
      return (
        '<div class="trend-card" data-tag="' + it.tag + '" style="--cat-color:' + catColor(it.category) + '">' +
        '<div class="tc-head">' +
        '<span class="tc-tag">' + it.label + (it.ksa ? ' <span class="tc-ksa">★</span>' : "") + "</span>" +
        '<span class="tc-rank">#' + it.rank + "</span>" +
        "</div>" +
        '<div class="tc-meta"><span class="tc-cat"><span class="dot" style="background:' +
        catColor(it.category) + '"></span>' + catIcon(it.category) + " " + catName(it.category) + "</span></div>" +
        '<div class="tc-heat"><span style="width:' + it.heat + '%"></span></div>' +
        '<div class="tc-heatval">درجة الرواج ' + it.heat + " / 100</div>" +
        "</div>"
      );
    }).join("");
    Array.prototype.forEach.call(listGrid.querySelectorAll(".trend-card"), function (card) {
      card.addEventListener("click", function () { openDrawer(byTag(card.dataset.tag)); });
    });
  }

  function byTag(tag) {
    for (var i = 0; i < ITEMS.length; i++) if (ITEMS[i].tag === tag) return ITEMS[i];
    return null;
  }

  // =================================================================
  // Drawer
  // =================================================================
  var drawer = $("#drawer");
  var drawerBody = $("#drawerBody");
  var drawerScrim = $("#drawerScrim");
  function openDrawer(it) {
    if (!it) return;
    drawerBody.innerHTML =
      '<div class="d-emoji">' + catIcon(it.category) + "</div>" +
      '<div class="d-tag">' + it.label + "</div>" +
      '<div class="d-cat"><span class="dot" style="background:' + catColor(it.category) + '"></span>' +
      catName(it.category) + "</div>" +
      (it.ksa ? '<div class="d-ksa">★ بارز للجمهور السعودي</div>' : '<div style="height:10px"></div>') +
      '<div class="d-grid">' +
      '<div class="d-stat"><div class="v">#' + it.rank + '</div><div class="l">الترتيب العالمي</div></div>' +
      '<div class="d-stat"><div class="v">' + it.heat + '</div><div class="l">درجة الرواج / 100</div></div>' +
      "</div>" +
      '<div class="d-heat"><span style="width:' + it.heat + '%"></span></div>' +
      '<a class="d-link" href="' + it.url + '" target="_blank" rel="noopener">▶ افتح الهاشتاق على تيك توك</a>' +
      '<p class="d-note">الترتيب من قائمة هاشتاقات تيك توك الرائجة عالمياً عبر Trends MCP (بتاريخ ' +
      fmtDate(DATA.meta.as_of) + "). درجة الرواج محسوبة من موضع الهاشتاق في القائمة.</p>";
    drawer.hidden = false;
    drawerScrim.hidden = false;
  }
  function closeDrawer() { drawer.hidden = true; drawerScrim.hidden = true; }
  $("#drawerClose").addEventListener("click", closeDrawer);
  drawerScrim.addEventListener("click", closeDrawer);
  document.addEventListener("keydown", function (e) { if (e.key === "Escape") closeDrawer(); });

  // =================================================================
  // SWARM (canvas physics)
  // =================================================================
  var canvas = $("#swarm");
  var ctx = canvas.getContext("2d");
  var W = 0, H = 0, dpr = 1;
  var nodes = [];
  var mouse = { x: -1e4, y: -1e4, active: false };
  var hovered = null;
  var hintEl = $("#swarmHint");
  var tooltip = $("#tooltip");
  var swarmEmpty = $("#swarmEmpty");

  function radiusFor(heat) {
    var rMin = 15, rMax = 60;
    return rMin + (rMax - rMin) * Math.sqrt(heat / 100);
  }

  function buildNodes() {
    nodes = ITEMS.map(function (it, i) {
      var r = radiusFor(it.heat);
      return {
        item: it,
        x: W * (0.2 + 0.6 * Math.random()),
        y: H * (0.2 + 0.6 * Math.random()),
        vx: (Math.random() - 0.5) * 0.4,
        vy: (Math.random() - 0.5) * 0.4,
        r: r,
        curR: r * 0.2,
        alpha: 0,
        phase: Math.random() * Math.PI * 2,
        color: catColor(it.category),
        visible: true,
      };
    });
  }

  function resize() {
    var rect = canvas.getBoundingClientRect();
    dpr = Math.min(window.devicePixelRatio || 1, 2);
    W = rect.width; H = rect.height;
    canvas.width = Math.round(W * dpr);
    canvas.height = Math.round(H * dpr);
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    if (!nodes.length) buildNodes();
  }

  function updateVisibility() {
    var anyVisible = false;
    nodes.forEach(function (n) {
      n.visible = matches(n.item);
      if (n.visible) anyVisible = true;
    });
    swarmEmpty.hidden = anyVisible;
  }

  // physics step
  var t = 0;
  function step() {
    t += 0.016;
    var cx = W / 2, cy = H / 2;

    for (var i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      // smooth grow/shrink + fade
      var targetR = n.visible ? n.r : 0.001;
      n.curR += (targetR - n.curR) * 0.12;
      n.alpha += ((n.visible ? 1 : 0) - n.alpha) * 0.12;
      if (!n.visible) continue;

      // gentle gravity to centre
      n.vx += (cx - n.x) * 0.0010;
      n.vy += (cy - n.y) * 0.0010;
      // organic wander
      n.vx += Math.cos(t * 0.6 + n.phase) * 0.018;
      n.vy += Math.sin(t * 0.5 + n.phase * 1.3) * 0.018;

      // pointer repulsion
      if (mouse.active) {
        var mdx = n.x - mouse.x, mdy = n.y - mouse.y;
        var md = Math.sqrt(mdx * mdx + mdy * mdy) || 1;
        var reach = 120 + n.curR;
        if (md < reach) {
          var push = (1 - md / reach) * 1.6;
          n.vx += (mdx / md) * push;
          n.vy += (mdy / md) * push;
        }
      }
    }

    // collisions (visible only)
    for (var a = 0; a < nodes.length; a++) {
      var na = nodes[a];
      if (!na.visible) continue;
      for (var b = a + 1; b < nodes.length; b++) {
        var nb = nodes[b];
        if (!nb.visible) continue;
        var dx = nb.x - na.x, dy = nb.y - na.y;
        var dist = Math.sqrt(dx * dx + dy * dy) || 0.01;
        var min = na.curR + nb.curR + 6;
        if (dist < min) {
          var overlap = (min - dist) / dist * 0.5;
          var ox = dx * overlap, oy = dy * overlap;
          na.x -= ox; na.y -= oy;
          nb.x += ox; nb.y += oy;
        }
      }
    }

    // integrate + bounds
    for (var k = 0; k < nodes.length; k++) {
      var p = nodes[k];
      if (!p.visible) continue;
      p.vx *= 0.86; p.vy *= 0.86;
      var sp = Math.sqrt(p.vx * p.vx + p.vy * p.vy);
      if (sp > 3.4) { p.vx = p.vx / sp * 3.4; p.vy = p.vy / sp * 3.4; }
      p.x += p.vx; p.y += p.vy;
      var pad = p.curR + 4;
      if (p.x < pad) { p.x = pad; p.vx *= -0.5; }
      if (p.x > W - pad) { p.x = W - pad; p.vx *= -0.5; }
      if (p.y < pad) { p.y = pad; p.vy *= -0.5; }
      if (p.y > H - pad) { p.y = H - pad; p.vy *= -0.5; }
    }
  }

  function draw() {
    ctx.clearRect(0, 0, W, H);
    for (var i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      if (n.curR < 0.6 || n.alpha < 0.02) continue;
      var isHover = hovered === n;
      ctx.save();
      ctx.globalAlpha = n.alpha;

      // glow
      ctx.shadowColor = n.color;
      ctx.shadowBlur = isHover ? 30 : 14;

      // body
      var grad = ctx.createRadialGradient(
        n.x - n.curR * 0.3, n.y - n.curR * 0.3, n.curR * 0.1,
        n.x, n.y, n.curR
      );
      grad.addColorStop(0, mix(n.color, "#ffffff", 0.5));
      grad.addColorStop(0.55, n.color);
      grad.addColorStop(1, mix(n.color, "#05050a", 0.45));
      ctx.beginPath();
      ctx.arc(n.x, n.y, n.curR, 0, Math.PI * 2);
      ctx.fillStyle = grad;
      ctx.fill();

      ctx.shadowBlur = 0;
      // rim
      ctx.lineWidth = isHover ? 2.5 : 1;
      ctx.strokeStyle = isHover ? "rgba(255,255,255,0.9)" : "rgba(255,255,255,0.22)";
      ctx.stroke();

      // KSA star ring
      if (n.item.ksa) {
        ctx.beginPath();
        ctx.arc(n.x, n.y, n.curR + 4, -Math.PI * 0.75, -Math.PI * 0.25);
        ctx.strokeStyle = "#f5d547";
        ctx.lineWidth = 2.5;
        ctx.stroke();
        if (n.curR > 18) {
          ctx.fillStyle = "#f5d547";
          ctx.font = "11px Tajawal, sans-serif";
          ctx.textAlign = "center";
          ctx.fillText("★", n.x, n.y - n.curR - 3);
        }
      }

      // label
      if (n.curR > 23) {
        var fs = Math.max(10, Math.min(n.curR * 0.34, 15));
        ctx.font = "700 " + fs + "px Tajawal, sans-serif";
        ctx.fillStyle = "rgba(8,8,14,0.92)";
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        var label = n.item.tag;
        if (label.length > 11 && n.curR < 46) label = label.slice(0, 9) + "…";
        ctx.fillText(label, n.x, n.y);
      }
      ctx.restore();
    }
  }

  function loop() {
    step();
    draw();
    requestAnimationFrame(loop);
  }

  // colour mixing util (hex + hex)
  function mix(c1, c2, amt) {
    var a = hex(c1), b = hex(c2);
    var r = Math.round(a[0] + (b[0] - a[0]) * amt);
    var g = Math.round(a[1] + (b[1] - a[1]) * amt);
    var bl = Math.round(a[2] + (b[2] - a[2]) * amt);
    return "rgb(" + r + "," + g + "," + bl + ")";
  }
  function hex(h) {
    h = h.replace("#", "");
    if (h.length === 3) h = h[0] + h[0] + h[1] + h[1] + h[2] + h[2];
    return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
  }

  // ---- pointer interaction ----
  function pointerPos(e) {
    var rect = canvas.getBoundingClientRect();
    return { x: e.clientX - rect.left, y: e.clientY - rect.top, rect: rect };
  }
  function findHover(x, y) {
    var best = null, bestD = 1e9;
    for (var i = 0; i < nodes.length; i++) {
      var n = nodes[i];
      if (!n.visible || n.alpha < 0.5) continue;
      var dx = x - n.x, dy = y - n.y;
      var d = Math.sqrt(dx * dx + dy * dy);
      if (d <= n.curR && d < bestD) { bestD = d; best = n; }
    }
    return best;
  }
  canvas.addEventListener("pointermove", function (e) {
    var p = pointerPos(e);
    mouse.x = p.x; mouse.y = p.y; mouse.active = true;
    hovered = findHover(p.x, p.y);
    if (hovered) {
      hintEl.style.opacity = "0";
      var it = hovered.item;
      tooltip.innerHTML =
        '<div class="tt-tag">' + it.label + (it.ksa ? " ★" : "") + "</div>" +
        '<div class="tt-row"><span class="tt-cat"><span class="dot" style="background:' +
        catColor(it.category) + '"></span>' + catName(it.category) + "</span><span>#" + it.rank + "</span></div>" +
        '<div class="tt-row"><span>درجة الرواج</span><span>' + it.heat + "/100</span></div>";
      tooltip.style.left = (p.rect.left + hovered.x) + "px";
      tooltip.style.top = (p.rect.top + hovered.y - hovered.curR) + "px";
      tooltip.hidden = false;
      canvas.style.cursor = "pointer";
    } else {
      tooltip.hidden = true;
      canvas.style.cursor = "crosshair";
    }
  });
  canvas.addEventListener("pointerleave", function () {
    mouse.active = false; mouse.x = -1e4; mouse.y = -1e4;
    hovered = null; tooltip.hidden = true;
  });
  canvas.addEventListener("click", function (e) {
    var p = pointerPos(e);
    var hit = findHover(p.x, p.y);
    if (hit) openDrawer(hit.item);
  });

  // =================================================================
  // View toggle
  // =================================================================
  Array.prototype.forEach.call(document.querySelectorAll(".vt-btn"), function (btn) {
    btn.addEventListener("click", function () {
      var view = btn.dataset.view;
      if (view === state.view) return;
      state.view = view;
      Array.prototype.forEach.call(document.querySelectorAll(".vt-btn"), function (b) {
        var on = b === btn;
        b.classList.toggle("is-active", on);
        b.setAttribute("aria-selected", on ? "true" : "false");
      });
      $("#view-swarm").classList.toggle("is-active", view === "swarm");
      $("#view-swarm").hidden = view !== "swarm";
      $("#view-list").classList.toggle("is-active", view === "list");
      $("#view-list").hidden = view !== "list";
      if (view === "swarm") resize();
    });
  });

  // =================================================================
  // Filters wiring
  // =================================================================
  function applyFilters() {
    updateVisibility();
    renderStats();
    renderList();
  }

  var searchInput = $("#search");
  searchInput.addEventListener("input", function () {
    state.search = searchInput.value.trim();
    applyFilters();
  });

  var ksaBtn = $("#ksaToggle");
  ksaBtn.addEventListener("click", function () {
    state.ksaOnly = !state.ksaOnly;
    ksaBtn.setAttribute("aria-pressed", state.ksaOnly ? "true" : "false");
    applyFilters();
  });

  $("#resetBtn").addEventListener("click", function () {
    state.search = "";
    searchInput.value = "";
    state.ksaOnly = false;
    ksaBtn.setAttribute("aria-pressed", "false");
    state.activeCats = new Set(Object.keys(CATS));
    Array.prototype.forEach.call(legendEl.querySelectorAll(".cat-chip"), function (c) {
      c.classList.remove("is-off");
    });
    applyFilters();
  });

  // =================================================================
  // Boot
  // =================================================================
  buildLegend();
  renderStats();
  renderList();
  resize();
  updateVisibility();
  window.addEventListener("resize", resize);
  requestAnimationFrame(loop);
})();
