// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.
// Source: Trends MCP · get_top_trends · TikTok Trending Hashtags (as of 2026-05-15T22:01:29.316598+00:00)
window.TREND_DATA = {
  "meta": {
    "title": "ترندات تيك توك",
    "source": "Trends MCP · get_top_trends · TikTok Trending Hashtags",
    "scope": "global",
    "as_of": "2026-05-15T22:01:29.316598+00:00",
    "generated_at": "2026-06-13T23:11:15.281Z",
    "count": 98,
    "note_ar": "هذه القائمة مصدرها Trends MCP وهي قائمة هاشتاقات تيك توك الرائجة عالمياً. لا يوفّر المصدر فلتر دولة، لذلك التمييز الخاص بالجمهور السعودي تحريري للإبراز فقط."
  },
  "categories": {
    "sports": {
      "ar": "رياضة",
      "en": "Sports",
      "icon": "⚽",
      "color": "#25F4EE"
    },
    "music": {
      "ar": "موسيقى",
      "en": "Music",
      "icon": "🎵",
      "color": "#FE2C55"
    },
    "entertainment": {
      "ar": "ترفيه",
      "en": "Entertainment",
      "icon": "🎬",
      "color": "#A66BFF"
    },
    "gaming": {
      "ar": "ألعاب",
      "en": "Gaming",
      "icon": "🎮",
      "color": "#5B8CFF"
    },
    "beauty": {
      "ar": "جمال",
      "en": "Beauty",
      "icon": "💄",
      "color": "#FF6FB5"
    },
    "health": {
      "ar": "صحة",
      "en": "Health",
      "icon": "🩺",
      "color": "#3DDC97"
    },
    "education": {
      "ar": "تعليم",
      "en": "Education",
      "icon": "🎓",
      "color": "#FFB454"
    },
    "tech": {
      "ar": "تقنية",
      "en": "Tech",
      "icon": "💻",
      "color": "#00D1B2"
    },
    "shopping": {
      "ar": "تسوّق",
      "en": "Shopping",
      "icon": "🛍️",
      "color": "#FF8A5C"
    },
    "creator": {
      "ar": "صنّاع المحتوى",
      "en": "Creators",
      "icon": "✨",
      "color": "#F5D547"
    },
    "food": {
      "ar": "طعام",
      "en": "Food",
      "icon": "🍓",
      "color": "#FF5C7A"
    },
    "lifestyle": {
      "ar": "لايف ستايل",
      "en": "Lifestyle",
      "icon": "🌿",
      "color": "#7CE0C3"
    },
    "news": {
      "ar": "أخبار",
      "en": "News",
      "icon": "📰",
      "color": "#9AA7B8"
    },
    "kculture": {
      "ar": "الموجة الكورية",
      "en": "K-Culture",
      "icon": "🇰🇷",
      "color": "#FF4D8D"
    },
    "books": {
      "ar": "كتب",
      "en": "Books",
      "icon": "📚",
      "color": "#C792EA"
    },
    "meme": {
      "ar": "ميمز",
      "en": "Memes",
      "icon": "😂",
      "color": "#FFD93D"
    },
    "business": {
      "ar": "أعمال ومال",
      "en": "Business",
      "icon": "💼",
      "color": "#6FCF97"
    },
    "other": {
      "ar": "متنوّع",
      "en": "Other",
      "icon": "＃",
      "color": "#7E8AA0"
    }
  },
  "breakdown": [
    {
      "key": "entertainment",
      "ar": "ترفيه",
      "en": "Entertainment",
      "icon": "🎬",
      "color": "#A66BFF",
      "count": 17
    },
    {
      "key": "sports",
      "ar": "رياضة",
      "en": "Sports",
      "icon": "⚽",
      "color": "#25F4EE",
      "count": 11
    },
    {
      "key": "music",
      "ar": "موسيقى",
      "en": "Music",
      "icon": "🎵",
      "color": "#FE2C55",
      "count": 8
    },
    {
      "key": "creator",
      "ar": "صنّاع المحتوى",
      "en": "Creators",
      "icon": "✨",
      "color": "#F5D547",
      "count": 8
    },
    {
      "key": "lifestyle",
      "ar": "لايف ستايل",
      "en": "Lifestyle",
      "icon": "🌿",
      "color": "#7CE0C3",
      "count": 8
    },
    {
      "key": "other",
      "ar": "متنوّع",
      "en": "Other",
      "icon": "＃",
      "color": "#7E8AA0",
      "count": 8
    },
    {
      "key": "gaming",
      "ar": "ألعاب",
      "en": "Gaming",
      "icon": "🎮",
      "color": "#5B8CFF",
      "count": 6
    },
    {
      "key": "health",
      "ar": "صحة",
      "en": "Health",
      "icon": "🩺",
      "color": "#3DDC97",
      "count": 5
    },
    {
      "key": "books",
      "ar": "كتب",
      "en": "Books",
      "icon": "📚",
      "color": "#C792EA",
      "count": 4
    },
    {
      "key": "meme",
      "ar": "ميمز",
      "en": "Memes",
      "icon": "😂",
      "color": "#FFD93D",
      "count": 4
    },
    {
      "key": "education",
      "ar": "تعليم",
      "en": "Education",
      "icon": "🎓",
      "color": "#FFB454",
      "count": 3
    },
    {
      "key": "shopping",
      "ar": "تسوّق",
      "en": "Shopping",
      "icon": "🛍️",
      "color": "#FF8A5C",
      "count": 3
    },
    {
      "key": "news",
      "ar": "أخبار",
      "en": "News",
      "icon": "📰",
      "color": "#9AA7B8",
      "count": 3
    },
    {
      "key": "kculture",
      "ar": "الموجة الكورية",
      "en": "K-Culture",
      "icon": "🇰🇷",
      "color": "#FF4D8D",
      "count": 3
    },
    {
      "key": "beauty",
      "ar": "جمال",
      "en": "Beauty",
      "icon": "💄",
      "color": "#FF6FB5",
      "count": 2
    },
    {
      "key": "food",
      "ar": "طعام",
      "en": "Food",
      "icon": "🍓",
      "color": "#FF5C7A",
      "count": 2
    },
    {
      "key": "business",
      "ar": "أعمال ومال",
      "en": "Business",
      "icon": "💼",
      "color": "#6FCF97",
      "count": 2
    },
    {
      "key": "tech",
      "ar": "تقنية",
      "en": "Tech",
      "icon": "💻",
      "color": "#00D1B2",
      "count": 1
    }
  ],
  "items": [
    {
      "rank": 1,
      "tag": "justgolive",
      "label": "#justgolive",
      "category": "creator",
      "heat": 100,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/justgolive"
    },
    {
      "rank": 2,
      "tag": "sidehustlelive",
      "label": "#sidehustlelive",
      "category": "business",
      "heat": 99,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/sidehustlelive"
    },
    {
      "rank": 3,
      "tag": "tiktokshopmemorialday",
      "label": "#tiktokshopmemorialday",
      "category": "shopping",
      "heat": 98,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/tiktokshopmemorialday"
    },
    {
      "rank": 4,
      "tag": "worldcup",
      "label": "#worldcup",
      "category": "sports",
      "heat": 97,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/worldcup"
    },
    {
      "rank": 5,
      "tag": "iceman",
      "label": "#iceman",
      "category": "entertainment",
      "heat": 96,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/iceman"
    },
    {
      "rank": 6,
      "tag": "usebloomlearntoinvest",
      "label": "#usebloomlearntoinvest",
      "category": "business",
      "heat": 95,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/usebloomlearntoinvest"
    },
    {
      "rank": 7,
      "tag": "dontoliver",
      "label": "#dontoliver",
      "category": "music",
      "heat": 94,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/dontoliver"
    },
    {
      "rank": 8,
      "tag": "footbal",
      "label": "#footbal",
      "category": "sports",
      "heat": 93,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/footbal"
    },
    {
      "rank": 9,
      "tag": "oneiy",
      "label": "#oneiy",
      "category": "other",
      "heat": 92,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/oneiy"
    },
    {
      "rank": 10,
      "tag": "primevideo",
      "label": "#primevideo",
      "category": "entertainment",
      "heat": 91,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/primevideo"
    },
    {
      "rank": 11,
      "tag": "memorialday",
      "label": "#memorialday",
      "category": "lifestyle",
      "heat": 90,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/memorialday"
    },
    {
      "rank": 12,
      "tag": "melissa",
      "label": "#melissa",
      "category": "other",
      "heat": 89,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/melissa"
    },
    {
      "rank": 13,
      "tag": "pethealth",
      "label": "#pethealth",
      "category": "health",
      "heat": 88,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/pethealth"
    },
    {
      "rank": 14,
      "tag": "jamescharles",
      "label": "#jamescharles",
      "category": "beauty",
      "heat": 87,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/jamescharles"
    },
    {
      "rank": 15,
      "tag": "offcampus",
      "label": "#offcampus",
      "category": "books",
      "heat": 86,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/offcampus"
    },
    {
      "rank": 16,
      "tag": "georgieandmandy",
      "label": "#georgieandmandy",
      "category": "entertainment",
      "heat": 85,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/georgieandmandy"
    },
    {
      "rank": 17,
      "tag": "edclasvegas",
      "label": "#edclasvegas",
      "category": "music",
      "heat": 84,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/edclasvegas"
    },
    {
      "rank": 18,
      "tag": "wipwednesday",
      "label": "#wipwednesday",
      "category": "creator",
      "heat": 83,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/wipwednesday"
    },
    {
      "rank": 19,
      "tag": "insideout",
      "label": "#insideout",
      "category": "entertainment",
      "heat": 82,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/insideout"
    },
    {
      "rank": 20,
      "tag": "boxen",
      "label": "#boxen",
      "category": "sports",
      "heat": 81,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/boxen"
    },
    {
      "rank": 21,
      "tag": "hotflashes",
      "label": "#hotflashes",
      "category": "health",
      "heat": 80,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/hotflashes"
    },
    {
      "rank": 22,
      "tag": "formel1",
      "label": "#formel1",
      "category": "sports",
      "heat": 79,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/formel1"
    },
    {
      "rank": 23,
      "tag": "kashpatel",
      "label": "#kashpatel",
      "category": "news",
      "heat": 78,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/kashpatel"
    },
    {
      "rank": 24,
      "tag": "niallhoran",
      "label": "#niallhoran",
      "category": "music",
      "heat": 77,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/niallhoran"
    },
    {
      "rank": 25,
      "tag": "mundial2026",
      "label": "#mundial2026",
      "category": "sports",
      "heat": 76,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/mundial2026"
    },
    {
      "rank": 26,
      "tag": "kevinhart",
      "label": "#kevinhart",
      "category": "entertainment",
      "heat": 74,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/kevinhart"
    },
    {
      "rank": 27,
      "tag": "wednesdayvibes",
      "label": "#wednesdayvibes",
      "category": "lifestyle",
      "heat": 73,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/wednesdayvibes"
    },
    {
      "rank": 28,
      "tag": "senioritis",
      "label": "#senioritis",
      "category": "education",
      "heat": 72,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/senioritis"
    },
    {
      "rank": 29,
      "tag": "devilmaycry",
      "label": "#devilmaycry",
      "category": "gaming",
      "heat": 71,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/devilmaycry"
    },
    {
      "rank": 30,
      "tag": "vidaderancho",
      "label": "#vidaderancho",
      "category": "lifestyle",
      "heat": 70,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/vidaderancho"
    },
    {
      "rank": 31,
      "tag": "datacenter",
      "label": "#datacenter",
      "category": "tech",
      "heat": 69,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/datacenter"
    },
    {
      "rank": 32,
      "tag": "punisher",
      "label": "#punisher",
      "category": "entertainment",
      "heat": 68,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/punisher"
    },
    {
      "rank": 33,
      "tag": "ellekennedy",
      "label": "#ellekennedy",
      "category": "books",
      "heat": 67,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/ellekennedy"
    },
    {
      "rank": 34,
      "tag": "menopausia",
      "label": "#menopausia",
      "category": "health",
      "heat": 66,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/menopausia"
    },
    {
      "rank": 35,
      "tag": "octane",
      "label": "#octane",
      "category": "gaming",
      "heat": 65,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/octane"
    },
    {
      "rank": 36,
      "tag": "dmc",
      "label": "#dmc",
      "category": "gaming",
      "heat": 64,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/dmc"
    },
    {
      "rank": 37,
      "tag": "boynextdoor",
      "label": "#boynextdoor",
      "category": "kculture",
      "heat": 63,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/boynextdoor"
    },
    {
      "rank": 38,
      "tag": "steviewonder",
      "label": "#steviewonder",
      "category": "music",
      "heat": 62,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/steviewonder"
    },
    {
      "rank": 39,
      "tag": "subnautica",
      "label": "#subnautica",
      "category": "gaming",
      "heat": 61,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/subnautica"
    },
    {
      "rank": 40,
      "tag": "offcampusseries",
      "label": "#offcampusseries",
      "category": "books",
      "heat": 60,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/offcampusseries"
    },
    {
      "rank": 41,
      "tag": "tiktokshopdealsforyou",
      "label": "#tiktokshopdealsforyou",
      "category": "shopping",
      "heat": 59,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/tiktokshopdealsforyou"
    },
    {
      "rank": 42,
      "tag": "goodomens",
      "label": "#goodomens",
      "category": "entertainment",
      "heat": 58,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/goodomens"
    },
    {
      "rank": 43,
      "tag": "fakenewspranktemplate",
      "label": "#fakenewspranktemplate",
      "category": "meme",
      "heat": 57,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/fakenewspranktemplate"
    },
    {
      "rank": 44,
      "tag": "fakenewspranktutorial",
      "label": "#fakenewspranktutorial",
      "category": "meme",
      "heat": 56,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/fakenewspranktutorial"
    },
    {
      "rank": 45,
      "tag": "howtodothefakenewsprank",
      "label": "#howtodothefakenewsprank",
      "category": "meme",
      "heat": 55,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/howtodothefakenewsprank"
    },
    {
      "rank": 46,
      "tag": "may15",
      "label": "#may15",
      "category": "other",
      "heat": 54,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/may15"
    },
    {
      "rank": 47,
      "tag": "ovulation",
      "label": "#ovulation",
      "category": "health",
      "heat": 53,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/ovulation"
    },
    {
      "rank": 48,
      "tag": "garrettgraham",
      "label": "#garrettgraham",
      "category": "other",
      "heat": 52,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/garrettgraham"
    },
    {
      "rank": 49,
      "tag": "perimenopausia",
      "label": "#perimenopausia",
      "category": "health",
      "heat": 51,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/perimenopausia"
    },
    {
      "rank": 50,
      "tag": "dante",
      "label": "#dante",
      "category": "gaming",
      "heat": 50,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/dante"
    },
    {
      "rank": 51,
      "tag": "deportesentiktok",
      "label": "#deportesentiktok",
      "category": "sports",
      "heat": 49,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/deportesentiktok"
    },
    {
      "rank": 52,
      "tag": "deenthegreat",
      "label": "#deenthegreat",
      "category": "creator",
      "heat": 48,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/deenthegreat"
    },
    {
      "rank": 53,
      "tag": "thedeal",
      "label": "#thedeal",
      "category": "entertainment",
      "heat": 47,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/thedeal"
    },
    {
      "rank": 54,
      "tag": "eurovision",
      "label": "#eurovision",
      "category": "music",
      "heat": 46,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/eurovision"
    },
    {
      "rank": 55,
      "tag": "bistrohuddy",
      "label": "#bistrohuddy",
      "category": "food",
      "heat": 45,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/bistrohuddy"
    },
    {
      "rank": 56,
      "tag": "coronavirus",
      "label": "#coronavirus",
      "category": "news",
      "heat": 44,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/coronavirus"
    },
    {
      "rank": 57,
      "tag": "dancevibes",
      "label": "#dancevibes",
      "category": "music",
      "heat": 43,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/dancevibes"
    },
    {
      "rank": 58,
      "tag": "bountyhunter",
      "label": "#bountyhunter",
      "category": "entertainment",
      "heat": 42,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/bountyhunter"
    },
    {
      "rank": 59,
      "tag": "builders",
      "label": "#builders",
      "category": "lifestyle",
      "heat": 41,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/builders"
    },
    {
      "rank": 60,
      "tag": "thepunisher",
      "label": "#thepunisher",
      "category": "entertainment",
      "heat": 40,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/thepunisher"
    },
    {
      "rank": 61,
      "tag": "memorialdayweekend",
      "label": "#memorialdayweekend",
      "category": "lifestyle",
      "heat": 39,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/memorialdayweekend"
    },
    {
      "rank": 62,
      "tag": "summerberryrefresher",
      "label": "#summerberryrefresher",
      "category": "food",
      "heat": 38,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/summerberryrefresher"
    },
    {
      "rank": 63,
      "tag": "ajo",
      "label": "#ajo",
      "category": "other",
      "heat": 37,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/ajo"
    },
    {
      "rank": 64,
      "tag": "grizzlies",
      "label": "#grizzlies",
      "category": "sports",
      "heat": 36,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/grizzlies"
    },
    {
      "rank": 65,
      "tag": "memphisgrizzlies",
      "label": "#memphisgrizzlies",
      "category": "sports",
      "heat": 35,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/memphisgrizzlies"
    },
    {
      "rank": 66,
      "tag": "offcampusellekennedy",
      "label": "#offcampusellekennedy",
      "category": "books",
      "heat": 34,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/offcampusellekennedy"
    },
    {
      "rank": 67,
      "tag": "hannahwells",
      "label": "#hannahwells",
      "category": "entertainment",
      "heat": 33,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/hannahwells"
    },
    {
      "rank": 68,
      "tag": "florentinoperez",
      "label": "#florentinoperez",
      "category": "sports",
      "heat": 32,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/florentinoperez"
    },
    {
      "rank": 69,
      "tag": "animalsworld",
      "label": "#animalsworld",
      "category": "lifestyle",
      "heat": 31,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/animalsworld"
    },
    {
      "rank": 70,
      "tag": "juliofoolio",
      "label": "#juliofoolio",
      "category": "music",
      "heat": 30,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/juliofoolio"
    },
    {
      "rank": 71,
      "tag": "jonbernthal",
      "label": "#jonbernthal",
      "category": "entertainment",
      "heat": 29,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/jonbernthal"
    },
    {
      "rank": 72,
      "tag": "goodomens3",
      "label": "#goodomens3",
      "category": "entertainment",
      "heat": 28,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/goodomens3"
    },
    {
      "rank": 73,
      "tag": "frankcastle",
      "label": "#frankcastle",
      "category": "entertainment",
      "heat": 27,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/frankcastle"
    },
    {
      "rank": 74,
      "tag": "deandilaurentis",
      "label": "#deandilaurentis",
      "category": "entertainment",
      "heat": 26,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/deandilaurentis"
    },
    {
      "rank": 75,
      "tag": "speedup",
      "label": "#speedup",
      "category": "music",
      "heat": 24,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/speedup"
    },
    {
      "rank": 76,
      "tag": "fypuk",
      "label": "#fypuk",
      "category": "creator",
      "heat": 23,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/fypuk"
    },
    {
      "rank": 77,
      "tag": "aplang",
      "label": "#aplang",
      "category": "education",
      "heat": 22,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/aplang"
    },
    {
      "rank": 78,
      "tag": "rosesarered",
      "label": "#rosesarered",
      "category": "meme",
      "heat": 21,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/rosesarered"
    },
    {
      "rank": 79,
      "tag": "tiktokgrowthchallenge",
      "label": "#tiktokgrowthchallenge",
      "category": "creator",
      "heat": 20,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/tiktokgrowthchallenge"
    },
    {
      "rank": 80,
      "tag": "may13",
      "label": "#may13",
      "category": "other",
      "heat": 19,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/may13"
    },
    {
      "rank": 81,
      "tag": "chudthebuilder",
      "label": "#chudthebuilder",
      "category": "creator",
      "heat": 18,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/chudthebuilder"
    },
    {
      "rank": 82,
      "tag": "subnautica2",
      "label": "#subnautica2",
      "category": "gaming",
      "heat": 17,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/subnautica2"
    },
    {
      "rank": 83,
      "tag": "georgecooper",
      "label": "#georgecooper",
      "category": "entertainment",
      "heat": 16,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/georgecooper"
    },
    {
      "rank": 84,
      "tag": "chelseahandler",
      "label": "#chelseahandler",
      "category": "entertainment",
      "heat": 15,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/chelseahandler"
    },
    {
      "rank": 85,
      "tag": "adrienbroner",
      "label": "#adrienbroner",
      "category": "sports",
      "heat": 14,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/adrienbroner"
    },
    {
      "rank": 86,
      "tag": "aplangexam",
      "label": "#aplangexam",
      "category": "education",
      "heat": 13,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/aplangexam"
    },
    {
      "rank": 87,
      "tag": "alexmurdaugh",
      "label": "#alexmurdaugh",
      "category": "news",
      "heat": 12,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/alexmurdaugh"
    },
    {
      "rank": 88,
      "tag": "seangathright",
      "label": "#seangathright",
      "category": "creator",
      "heat": 11,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/seangathright"
    },
    {
      "rank": 89,
      "tag": "koreantrend",
      "label": "#koreantrend",
      "category": "kculture",
      "heat": 10,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/koreantrend"
    },
    {
      "rank": 90,
      "tag": "daidai",
      "label": "#daidai",
      "category": "other",
      "heat": 9,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/daidai"
    },
    {
      "rank": 91,
      "tag": "capcutnow",
      "label": "#capcutnow",
      "category": "creator",
      "heat": 8,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/capcutnow"
    },
    {
      "rank": 92,
      "tag": "seniorfit",
      "label": "#seniorfit",
      "category": "lifestyle",
      "heat": 7,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/seniorfit"
    },
    {
      "rank": 93,
      "tag": "koreabaseball",
      "label": "#koreabaseball",
      "category": "sports",
      "heat": 6,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/koreabaseball"
    },
    {
      "rank": 94,
      "tag": "koreavibes",
      "label": "#koreavibes",
      "category": "kculture",
      "heat": 5,
      "ksa": true,
      "url": "https://www.tiktok.com/tag/koreavibes"
    },
    {
      "rank": 95,
      "tag": "jamescharlesdrama",
      "label": "#jamescharlesdrama",
      "category": "beauty",
      "heat": 4,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/jamescharlesdrama"
    },
    {
      "rank": 96,
      "tag": "pmos",
      "label": "#pmos",
      "category": "other",
      "heat": 3,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/pmos"
    },
    {
      "rank": 97,
      "tag": "seniorfits",
      "label": "#seniorfits",
      "category": "lifestyle",
      "heat": 2,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/seniorfits"
    },
    {
      "rank": 98,
      "tag": "multicolorcasualset",
      "label": "#multicolorcasualset",
      "category": "shopping",
      "heat": 1,
      "ksa": false,
      "url": "https://www.tiktok.com/tag/multicolorcasualset"
    }
  ]
};
