// AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.
// Hashtags: Trends MCP · get_top_trends · TikTok Trending Hashtags (as of 2026-05-15T22:01:29.316598+00:00)
// Searches: Trends MCP · get_top_trends · Google Trends (as of 2026-06-13T22:01:40.312818+00:00)
window.TREND_DATA = {
  "meta": {
    "title": "ترندات تيك توك",
    "generated_at": "2026-06-13T23:40:22.388Z",
    "note_ar": "منصة ترندات تيك توك — البيانات حية من Trends MCP. لا يوفّر المصدر فلتر دولة، لذا التمييز الخاص بالجمهور السعودي تحريري للإبراز فقط."
  },
  "categories": {
    "sports": {
      "ar": "رياضة",
      "en": "Sports",
      "icon": "⚽",
      "color": "#25F4EE"
    },
    "music": {
      "ar": "موسيقى",
      "en": "Music",
      "icon": "🎵",
      "color": "#FE2C55"
    },
    "entertainment": {
      "ar": "ترفيه",
      "en": "Entertainment",
      "icon": "🎬",
      "color": "#A66BFF"
    },
    "gaming": {
      "ar": "ألعاب",
      "en": "Gaming",
      "icon": "🎮",
      "color": "#5B8CFF"
    },
    "beauty": {
      "ar": "جمال",
      "en": "Beauty",
      "icon": "💄",
      "color": "#FF6FB5"
    },
    "health": {
      "ar": "صحة",
      "en": "Health",
      "icon": "🩺",
      "color": "#3DDC97"
    },
    "education": {
      "ar": "تعليم",
      "en": "Education",
      "icon": "🎓",
      "color": "#FFB454"
    },
    "tech": {
      "ar": "تقنية",
      "en": "Tech",
      "icon": "💻",
      "color": "#00D1B2"
    },
    "shopping": {
      "ar": "تسوّق",
      "en": "Shopping",
      "icon": "🛍️",
      "color": "#FF8A5C"
    },
    "creator": {
      "ar": "صنّاع المحتوى",
      "en": "Creators",
      "icon": "✨",
      "color": "#F5D547"
    },
    "food": {
      "ar": "طعام",
      "en": "Food",
      "icon": "🍓",
      "color": "#FF5C7A"
    },
    "lifestyle": {
      "ar": "لايف ستايل",
      "en": "Lifestyle",
      "icon": "🌿",
      "color": "#7CE0C3"
    },
    "news": {
      "ar": "أخبار",
      "en": "News",
      "icon": "📰",
      "color": "#9AA7B8"
    },
    "kculture": {
      "ar": "الموجة الكورية",
      "en": "K-Culture",
      "icon": "🇰🇷",
      "color": "#FF4D8D"
    },
    "books": {
      "ar": "كتب",
      "en": "Books",
      "icon": "📚",
      "color": "#C792EA"
    },
    "meme": {
      "ar": "ميمز",
      "en": "Memes",
      "icon": "😂",
      "color": "#FFD93D"
    },
    "business": {
      "ar": "أعمال ومال",
      "en": "Business",
      "icon": "💼",
      "color": "#6FCF97"
    },
    "other": {
      "ar": "متنوّع",
      "en": "Other",
      "icon": "＃",
      "color": "#7E8AA0"
    }
  },
  "hashtags": {
    "source": "Trends MCP · get_top_trends · TikTok Trending Hashtags",
    "scope": "global",
    "as_of": "2026-05-15T22:01:29.316598+00:00",
    "count": 98,
    "note_ar": "قائمة هاشتاقات تيك توك الرائجة عالمياً عبر Trends MCP. درجة الرواج محسوبة من موضع الهاشتاق في القائمة.",
    "breakdown": [
      {
        "key": "entertainment",
        "ar": "ترفيه",
        "en": "Entertainment",
        "icon": "🎬",
        "color": "#A66BFF",
        "count": 17
      },
      {
        "key": "sports",
        "ar": "رياضة",
        "en": "Sports",
        "icon": "⚽",
        "color": "#25F4EE",
        "count": 11
      },
      {
        "key": "music",
        "ar": "موسيقى",
        "en": "Music",
        "icon": "🎵",
        "color": "#FE2C55",
        "count": 8
      },
      {
        "key": "creator",
        "ar": "صنّاع المحتوى",
        "en": "Creators",
        "icon": "✨",
        "color": "#F5D547",
        "count": 8
      },
      {
        "key": "lifestyle",
        "ar": "لايف ستايل",
        "en": "Lifestyle",
        "icon": "🌿",
        "color": "#7CE0C3",
        "count": 8
      },
      {
        "key": "other",
        "ar": "متنوّع",
        "en": "Other",
        "icon": "＃",
        "color": "#7E8AA0",
        "count": 8
      },
      {
        "key": "gaming",
        "ar": "ألعاب",
        "en": "Gaming",
        "icon": "🎮",
        "color": "#5B8CFF",
        "count": 6
      },
      {
        "key": "health",
        "ar": "صحة",
        "en": "Health",
        "icon": "🩺",
        "color": "#3DDC97",
        "count": 5
      },
      {
        "key": "books",
        "ar": "كتب",
        "en": "Books",
        "icon": "📚",
        "color": "#C792EA",
        "count": 4
      },
      {
        "key": "meme",
        "ar": "ميمز",
        "en": "Memes",
        "icon": "😂",
        "color": "#FFD93D",
        "count": 4
      },
      {
        "key": "education",
        "ar": "تعليم",
        "en": "Education",
        "icon": "🎓",
        "color": "#FFB454",
        "count": 3
      },
      {
        "key": "shopping",
        "ar": "تسوّق",
        "en": "Shopping",
        "icon": "🛍️",
        "color": "#FF8A5C",
        "count": 3
      },
      {
        "key": "news",
        "ar": "أخبار",
        "en": "News",
        "icon": "📰",
        "color": "#9AA7B8",
        "count": 3
      },
      {
        "key": "kculture",
        "ar": "الموجة الكورية",
        "en": "K-Culture",
        "icon": "🇰🇷",
        "color": "#FF4D8D",
        "count": 3
      },
      {
        "key": "beauty",
        "ar": "جمال",
        "en": "Beauty",
        "icon": "💄",
        "color": "#FF6FB5",
        "count": 2
      },
      {
        "key": "food",
        "ar": "طعام",
        "en": "Food",
        "icon": "🍓",
        "color": "#FF5C7A",
        "count": 2
      },
      {
        "key": "business",
        "ar": "أعمال ومال",
        "en": "Business",
        "icon": "💼",
        "color": "#6FCF97",
        "count": 2
      },
      {
        "key": "tech",
        "ar": "تقنية",
        "en": "Tech",
        "icon": "💻",
        "color": "#00D1B2",
        "count": 1
      }
    ],
    "items": [
      {
        "rank": 1,
        "tag": "justgolive",
        "label": "#justgolive",
        "category": "creator",
        "heat": 100,
        "ksa": false,
        "live": true,
        "url": "https://www.tiktok.com/tag/justgolive"
      },
      {
        "rank": 2,
        "tag": "sidehustlelive",
        "label": "#sidehustlelive",
        "category": "business",
        "heat": 99,
        "ksa": false,
        "live": true,
        "url": "https://www.tiktok.com/tag/sidehustlelive"
      },
      {
        "rank": 3,
        "tag": "tiktokshopmemorialday",
        "label": "#tiktokshopmemorialday",
        "category": "shopping",
        "heat": 98,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/tiktokshopmemorialday"
      },
      {
        "rank": 4,
        "tag": "worldcup",
        "label": "#worldcup",
        "category": "sports",
        "heat": 97,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/worldcup"
      },
      {
        "rank": 5,
        "tag": "iceman",
        "label": "#iceman",
        "category": "entertainment",
        "heat": 96,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/iceman"
      },
      {
        "rank": 6,
        "tag": "usebloomlearntoinvest",
        "label": "#usebloomlearntoinvest",
        "category": "business",
        "heat": 95,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/usebloomlearntoinvest"
      },
      {
        "rank": 7,
        "tag": "dontoliver",
        "label": "#dontoliver",
        "category": "music",
        "heat": 94,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/dontoliver"
      },
      {
        "rank": 8,
        "tag": "footbal",
        "label": "#footbal",
        "category": "sports",
        "heat": 93,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/footbal"
      },
      {
        "rank": 9,
        "tag": "oneiy",
        "label": "#oneiy",
        "category": "other",
        "heat": 92,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/oneiy"
      },
      {
        "rank": 10,
        "tag": "primevideo",
        "label": "#primevideo",
        "category": "entertainment",
        "heat": 91,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/primevideo"
      },
      {
        "rank": 11,
        "tag": "memorialday",
        "label": "#memorialday",
        "category": "lifestyle",
        "heat": 90,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/memorialday"
      },
      {
        "rank": 12,
        "tag": "melissa",
        "label": "#melissa",
        "category": "other",
        "heat": 89,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/melissa"
      },
      {
        "rank": 13,
        "tag": "pethealth",
        "label": "#pethealth",
        "category": "health",
        "heat": 88,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/pethealth"
      },
      {
        "rank": 14,
        "tag": "jamescharles",
        "label": "#jamescharles",
        "category": "beauty",
        "heat": 87,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/jamescharles"
      },
      {
        "rank": 15,
        "tag": "offcampus",
        "label": "#offcampus",
        "category": "books",
        "heat": 86,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/offcampus"
      },
      {
        "rank": 16,
        "tag": "georgieandmandy",
        "label": "#georgieandmandy",
        "category": "entertainment",
        "heat": 85,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/georgieandmandy"
      },
      {
        "rank": 17,
        "tag": "edclasvegas",
        "label": "#edclasvegas",
        "category": "music",
        "heat": 84,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/edclasvegas"
      },
      {
        "rank": 18,
        "tag": "wipwednesday",
        "label": "#wipwednesday",
        "category": "creator",
        "heat": 83,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/wipwednesday"
      },
      {
        "rank": 19,
        "tag": "insideout",
        "label": "#insideout",
        "category": "entertainment",
        "heat": 82,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/insideout"
      },
      {
        "rank": 20,
        "tag": "boxen",
        "label": "#boxen",
        "category": "sports",
        "heat": 81,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/boxen"
      },
      {
        "rank": 21,
        "tag": "hotflashes",
        "label": "#hotflashes",
        "category": "health",
        "heat": 80,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/hotflashes"
      },
      {
        "rank": 22,
        "tag": "formel1",
        "label": "#formel1",
        "category": "sports",
        "heat": 79,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/formel1"
      },
      {
        "rank": 23,
        "tag": "kashpatel",
        "label": "#kashpatel",
        "category": "news",
        "heat": 78,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/kashpatel"
      },
      {
        "rank": 24,
        "tag": "niallhoran",
        "label": "#niallhoran",
        "category": "music",
        "heat": 77,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/niallhoran"
      },
      {
        "rank": 25,
        "tag": "mundial2026",
        "label": "#mundial2026",
        "category": "sports",
        "heat": 76,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/mundial2026"
      },
      {
        "rank": 26,
        "tag": "kevinhart",
        "label": "#kevinhart",
        "category": "entertainment",
        "heat": 74,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/kevinhart"
      },
      {
        "rank": 27,
        "tag": "wednesdayvibes",
        "label": "#wednesdayvibes",
        "category": "lifestyle",
        "heat": 73,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/wednesdayvibes"
      },
      {
        "rank": 28,
        "tag": "senioritis",
        "label": "#senioritis",
        "category": "education",
        "heat": 72,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/senioritis"
      },
      {
        "rank": 29,
        "tag": "devilmaycry",
        "label": "#devilmaycry",
        "category": "gaming",
        "heat": 71,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/devilmaycry"
      },
      {
        "rank": 30,
        "tag": "vidaderancho",
        "label": "#vidaderancho",
        "category": "lifestyle",
        "heat": 70,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/vidaderancho"
      },
      {
        "rank": 31,
        "tag": "datacenter",
        "label": "#datacenter",
        "category": "tech",
        "heat": 69,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/datacenter"
      },
      {
        "rank": 32,
        "tag": "punisher",
        "label": "#punisher",
        "category": "entertainment",
        "heat": 68,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/punisher"
      },
      {
        "rank": 33,
        "tag": "ellekennedy",
        "label": "#ellekennedy",
        "category": "books",
        "heat": 67,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/ellekennedy"
      },
      {
        "rank": 34,
        "tag": "menopausia",
        "label": "#menopausia",
        "category": "health",
        "heat": 66,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/menopausia"
      },
      {
        "rank": 35,
        "tag": "octane",
        "label": "#octane",
        "category": "gaming",
        "heat": 65,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/octane"
      },
      {
        "rank": 36,
        "tag": "dmc",
        "label": "#dmc",
        "category": "gaming",
        "heat": 64,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/dmc"
      },
      {
        "rank": 37,
        "tag": "boynextdoor",
        "label": "#boynextdoor",
        "category": "kculture",
        "heat": 63,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/boynextdoor"
      },
      {
        "rank": 38,
        "tag": "steviewonder",
        "label": "#steviewonder",
        "category": "music",
        "heat": 62,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/steviewonder"
      },
      {
        "rank": 39,
        "tag": "subnautica",
        "label": "#subnautica",
        "category": "gaming",
        "heat": 61,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/subnautica"
      },
      {
        "rank": 40,
        "tag": "offcampusseries",
        "label": "#offcampusseries",
        "category": "books",
        "heat": 60,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/offcampusseries"
      },
      {
        "rank": 41,
        "tag": "tiktokshopdealsforyou",
        "label": "#tiktokshopdealsforyou",
        "category": "shopping",
        "heat": 59,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/tiktokshopdealsforyou"
      },
      {
        "rank": 42,
        "tag": "goodomens",
        "label": "#goodomens",
        "category": "entertainment",
        "heat": 58,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/goodomens"
      },
      {
        "rank": 43,
        "tag": "fakenewspranktemplate",
        "label": "#fakenewspranktemplate",
        "category": "meme",
        "heat": 57,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/fakenewspranktemplate"
      },
      {
        "rank": 44,
        "tag": "fakenewspranktutorial",
        "label": "#fakenewspranktutorial",
        "category": "meme",
        "heat": 56,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/fakenewspranktutorial"
      },
      {
        "rank": 45,
        "tag": "howtodothefakenewsprank",
        "label": "#howtodothefakenewsprank",
        "category": "meme",
        "heat": 55,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/howtodothefakenewsprank"
      },
      {
        "rank": 46,
        "tag": "may15",
        "label": "#may15",
        "category": "other",
        "heat": 54,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/may15"
      },
      {
        "rank": 47,
        "tag": "ovulation",
        "label": "#ovulation",
        "category": "health",
        "heat": 53,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/ovulation"
      },
      {
        "rank": 48,
        "tag": "garrettgraham",
        "label": "#garrettgraham",
        "category": "other",
        "heat": 52,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/garrettgraham"
      },
      {
        "rank": 49,
        "tag": "perimenopausia",
        "label": "#perimenopausia",
        "category": "health",
        "heat": 51,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/perimenopausia"
      },
      {
        "rank": 50,
        "tag": "dante",
        "label": "#dante",
        "category": "gaming",
        "heat": 50,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/dante"
      },
      {
        "rank": 51,
        "tag": "deportesentiktok",
        "label": "#deportesentiktok",
        "category": "sports",
        "heat": 49,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/deportesentiktok"
      },
      {
        "rank": 52,
        "tag": "deenthegreat",
        "label": "#deenthegreat",
        "category": "creator",
        "heat": 48,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/deenthegreat"
      },
      {
        "rank": 53,
        "tag": "thedeal",
        "label": "#thedeal",
        "category": "entertainment",
        "heat": 47,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/thedeal"
      },
      {
        "rank": 54,
        "tag": "eurovision",
        "label": "#eurovision",
        "category": "music",
        "heat": 46,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/eurovision"
      },
      {
        "rank": 55,
        "tag": "bistrohuddy",
        "label": "#bistrohuddy",
        "category": "food",
        "heat": 45,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/bistrohuddy"
      },
      {
        "rank": 56,
        "tag": "coronavirus",
        "label": "#coronavirus",
        "category": "news",
        "heat": 44,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/coronavirus"
      },
      {
        "rank": 57,
        "tag": "dancevibes",
        "label": "#dancevibes",
        "category": "music",
        "heat": 43,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/dancevibes"
      },
      {
        "rank": 58,
        "tag": "bountyhunter",
        "label": "#bountyhunter",
        "category": "entertainment",
        "heat": 42,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/bountyhunter"
      },
      {
        "rank": 59,
        "tag": "builders",
        "label": "#builders",
        "category": "lifestyle",
        "heat": 41,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/builders"
      },
      {
        "rank": 60,
        "tag": "thepunisher",
        "label": "#thepunisher",
        "category": "entertainment",
        "heat": 40,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/thepunisher"
      },
      {
        "rank": 61,
        "tag": "memorialdayweekend",
        "label": "#memorialdayweekend",
        "category": "lifestyle",
        "heat": 39,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/memorialdayweekend"
      },
      {
        "rank": 62,
        "tag": "summerberryrefresher",
        "label": "#summerberryrefresher",
        "category": "food",
        "heat": 38,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/summerberryrefresher"
      },
      {
        "rank": 63,
        "tag": "ajo",
        "label": "#ajo",
        "category": "other",
        "heat": 37,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/ajo"
      },
      {
        "rank": 64,
        "tag": "grizzlies",
        "label": "#grizzlies",
        "category": "sports",
        "heat": 36,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/grizzlies"
      },
      {
        "rank": 65,
        "tag": "memphisgrizzlies",
        "label": "#memphisgrizzlies",
        "category": "sports",
        "heat": 35,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/memphisgrizzlies"
      },
      {
        "rank": 66,
        "tag": "offcampusellekennedy",
        "label": "#offcampusellekennedy",
        "category": "books",
        "heat": 34,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/offcampusellekennedy"
      },
      {
        "rank": 67,
        "tag": "hannahwells",
        "label": "#hannahwells",
        "category": "entertainment",
        "heat": 33,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/hannahwells"
      },
      {
        "rank": 68,
        "tag": "florentinoperez",
        "label": "#florentinoperez",
        "category": "sports",
        "heat": 32,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/florentinoperez"
      },
      {
        "rank": 69,
        "tag": "animalsworld",
        "label": "#animalsworld",
        "category": "lifestyle",
        "heat": 31,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/animalsworld"
      },
      {
        "rank": 70,
        "tag": "juliofoolio",
        "label": "#juliofoolio",
        "category": "music",
        "heat": 30,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/juliofoolio"
      },
      {
        "rank": 71,
        "tag": "jonbernthal",
        "label": "#jonbernthal",
        "category": "entertainment",
        "heat": 29,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/jonbernthal"
      },
      {
        "rank": 72,
        "tag": "goodomens3",
        "label": "#goodomens3",
        "category": "entertainment",
        "heat": 28,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/goodomens3"
      },
      {
        "rank": 73,
        "tag": "frankcastle",
        "label": "#frankcastle",
        "category": "entertainment",
        "heat": 27,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/frankcastle"
      },
      {
        "rank": 74,
        "tag": "deandilaurentis",
        "label": "#deandilaurentis",
        "category": "entertainment",
        "heat": 26,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/deandilaurentis"
      },
      {
        "rank": 75,
        "tag": "speedup",
        "label": "#speedup",
        "category": "music",
        "heat": 24,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/speedup"
      },
      {
        "rank": 76,
        "tag": "fypuk",
        "label": "#fypuk",
        "category": "creator",
        "heat": 23,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/fypuk"
      },
      {
        "rank": 77,
        "tag": "aplang",
        "label": "#aplang",
        "category": "education",
        "heat": 22,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/aplang"
      },
      {
        "rank": 78,
        "tag": "rosesarered",
        "label": "#rosesarered",
        "category": "meme",
        "heat": 21,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/rosesarered"
      },
      {
        "rank": 79,
        "tag": "tiktokgrowthchallenge",
        "label": "#tiktokgrowthchallenge",
        "category": "creator",
        "heat": 20,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/tiktokgrowthchallenge"
      },
      {
        "rank": 80,
        "tag": "may13",
        "label": "#may13",
        "category": "other",
        "heat": 19,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/may13"
      },
      {
        "rank": 81,
        "tag": "chudthebuilder",
        "label": "#chudthebuilder",
        "category": "creator",
        "heat": 18,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/chudthebuilder"
      },
      {
        "rank": 82,
        "tag": "subnautica2",
        "label": "#subnautica2",
        "category": "gaming",
        "heat": 17,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/subnautica2"
      },
      {
        "rank": 83,
        "tag": "georgecooper",
        "label": "#georgecooper",
        "category": "entertainment",
        "heat": 16,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/georgecooper"
      },
      {
        "rank": 84,
        "tag": "chelseahandler",
        "label": "#chelseahandler",
        "category": "entertainment",
        "heat": 15,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/chelseahandler"
      },
      {
        "rank": 85,
        "tag": "adrienbroner",
        "label": "#adrienbroner",
        "category": "sports",
        "heat": 14,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/adrienbroner"
      },
      {
        "rank": 86,
        "tag": "aplangexam",
        "label": "#aplangexam",
        "category": "education",
        "heat": 13,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/aplangexam"
      },
      {
        "rank": 87,
        "tag": "alexmurdaugh",
        "label": "#alexmurdaugh",
        "category": "news",
        "heat": 12,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/alexmurdaugh"
      },
      {
        "rank": 88,
        "tag": "seangathright",
        "label": "#seangathright",
        "category": "creator",
        "heat": 11,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/seangathright"
      },
      {
        "rank": 89,
        "tag": "koreantrend",
        "label": "#koreantrend",
        "category": "kculture",
        "heat": 10,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/koreantrend"
      },
      {
        "rank": 90,
        "tag": "daidai",
        "label": "#daidai",
        "category": "other",
        "heat": 9,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/daidai"
      },
      {
        "rank": 91,
        "tag": "capcutnow",
        "label": "#capcutnow",
        "category": "creator",
        "heat": 8,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/capcutnow"
      },
      {
        "rank": 92,
        "tag": "seniorfit",
        "label": "#seniorfit",
        "category": "lifestyle",
        "heat": 7,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/seniorfit"
      },
      {
        "rank": 93,
        "tag": "koreabaseball",
        "label": "#koreabaseball",
        "category": "sports",
        "heat": 6,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/koreabaseball"
      },
      {
        "rank": 94,
        "tag": "koreavibes",
        "label": "#koreavibes",
        "category": "kculture",
        "heat": 5,
        "ksa": true,
        "live": false,
        "url": "https://www.tiktok.com/tag/koreavibes"
      },
      {
        "rank": 95,
        "tag": "jamescharlesdrama",
        "label": "#jamescharlesdrama",
        "category": "beauty",
        "heat": 4,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/jamescharlesdrama"
      },
      {
        "rank": 96,
        "tag": "pmos",
        "label": "#pmos",
        "category": "other",
        "heat": 3,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/pmos"
      },
      {
        "rank": 97,
        "tag": "seniorfits",
        "label": "#seniorfits",
        "category": "lifestyle",
        "heat": 2,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/seniorfits"
      },
      {
        "rank": 98,
        "tag": "multicolorcasualset",
        "label": "#multicolorcasualset",
        "category": "shopping",
        "heat": 1,
        "ksa": false,
        "live": false,
        "url": "https://www.tiktok.com/tag/multicolorcasualset"
      }
    ]
  },
  "searches": {
    "source": "Trends MCP · get_top_trends · Google Trends",
    "scope": "global",
    "as_of": "2026-06-13T22:01:40.312818+00:00",
    "count": 71,
    "note_ar": "Trends MCP لا يوفّر feed لترندات بحث تيك توك، لذا هذا القسم يعرض ترندات البحث من Google Trends (بيانات بحث حقيقية، عالمية وليست خاصة بتيك توك أو بالسعودية).",
    "items": [
      {
        "rank": 1,
        "srcRank": 1,
        "query": "spacex stock",
        "category": "tech",
        "heat": 100,
        "url": "https://www.google.com/search?q=spacex%20stock"
      },
      {
        "rank": 2,
        "srcRank": 2,
        "query": "karmelo anthony",
        "category": "news",
        "heat": 99,
        "url": "https://www.google.com/search?q=karmelo%20anthony"
      },
      {
        "rank": 3,
        "srcRank": 3,
        "query": "tornado watch",
        "category": "news",
        "heat": 97,
        "url": "https://www.google.com/search?q=tornado%20watch"
      },
      {
        "rank": 4,
        "srcRank": 4,
        "query": "heat advisory",
        "category": "news",
        "heat": 96,
        "url": "https://www.google.com/search?q=heat%20advisory"
      },
      {
        "rank": 5,
        "srcRank": 5,
        "query": "disclosure day",
        "category": "news",
        "heat": 94,
        "url": "https://www.google.com/search?q=disclosure%20day"
      },
      {
        "rank": 6,
        "srcRank": 6,
        "query": "whos playing today world cup",
        "category": "sports",
        "heat": 93,
        "url": "https://www.google.com/search?q=whos%20playing%20today%20world%20cup"
      },
      {
        "rank": 7,
        "srcRank": 7,
        "query": "is facebook down",
        "category": "tech",
        "heat": 92,
        "url": "https://www.google.com/search?q=is%20facebook%20down"
      },
      {
        "rank": 8,
        "srcRank": 8,
        "query": "yvette hinds mcdonald's lawsuit",
        "category": "business",
        "heat": 90,
        "url": "https://www.google.com/search?q=yvette%20hinds%20mcdonald's%20lawsuit"
      },
      {
        "rank": 9,
        "srcRank": 9,
        "query": "every year after",
        "category": "news",
        "heat": 89,
        "url": "https://www.google.com/search?q=every%20year%20after"
      },
      {
        "rank": 10,
        "srcRank": 10,
        "query": "southwest",
        "category": "business",
        "heat": 87,
        "url": "https://www.google.com/search?q=southwest"
      },
      {
        "rank": 11,
        "srcRank": 11,
        "query": "olivia rodrigo",
        "category": "music",
        "heat": 86,
        "url": "https://www.google.com/search?q=olivia%20rodrigo"
      },
      {
        "rank": 12,
        "srcRank": 12,
        "query": "cbs watson show cancellation",
        "category": "entertainment",
        "heat": 85,
        "url": "https://www.google.com/search?q=cbs%20watson%20show%20cancellation"
      },
      {
        "rank": 13,
        "srcRank": 13,
        "query": "sleeping bag",
        "category": "news",
        "heat": 83,
        "url": "https://www.google.com/search?q=sleeping%20bag"
      },
      {
        "rank": 14,
        "srcRank": 14,
        "query": "social security electronic benefits update",
        "category": "business",
        "heat": 82,
        "url": "https://www.google.com/search?q=social%20security%20electronic%20benefits%20update"
      },
      {
        "rank": 15,
        "srcRank": 15,
        "query": "simone biles",
        "category": "sports",
        "heat": 80,
        "url": "https://www.google.com/search?q=simone%20biles"
      },
      {
        "rank": 16,
        "srcRank": 16,
        "query": "papal",
        "category": "news",
        "heat": 79,
        "url": "https://www.google.com/search?q=papal"
      },
      {
        "rank": 17,
        "srcRank": 17,
        "query": "ariana grande tour",
        "category": "music",
        "heat": 77,
        "url": "https://www.google.com/search?q=ariana%20grande%20tour"
      },
      {
        "rank": 18,
        "srcRank": 18,
        "query": "chipotle bogo",
        "category": "business",
        "heat": 76,
        "url": "https://www.google.com/search?q=chipotle%20bogo"
      },
      {
        "rank": 19,
        "srcRank": 19,
        "query": "philippines earthquake",
        "category": "news",
        "heat": 75,
        "url": "https://www.google.com/search?q=philippines%20earthquake"
      },
      {
        "rank": 20,
        "srcRank": 20,
        "query": "nintendo direct",
        "category": "gaming",
        "heat": 73,
        "url": "https://www.google.com/search?q=nintendo%20direct"
      },
      {
        "rank": 21,
        "srcRank": 21,
        "query": "kristen welker",
        "category": "entertainment",
        "heat": 72,
        "url": "https://www.google.com/search?q=kristen%20welker"
      },
      {
        "rank": 22,
        "srcRank": 22,
        "query": "tony awards 2026",
        "category": "entertainment",
        "heat": 70,
        "url": "https://www.google.com/search?q=tony%20awards%202026"
      },
      {
        "rank": 23,
        "srcRank": 23,
        "query": "earthquake",
        "category": "news",
        "heat": 69,
        "url": "https://www.google.com/search?q=earthquake"
      },
      {
        "rank": 24,
        "srcRank": 24,
        "query": "love island voting",
        "category": "entertainment",
        "heat": 68,
        "url": "https://www.google.com/search?q=love%20island%20voting"
      },
      {
        "rank": 25,
        "srcRank": 25,
        "query": "wwdc",
        "category": "tech",
        "heat": 66,
        "url": "https://www.google.com/search?q=wwdc"
      },
      {
        "rank": 26,
        "srcRank": 26,
        "query": "tony awards",
        "category": "entertainment",
        "heat": 65,
        "url": "https://www.google.com/search?q=tony%20awards"
      },
      {
        "rank": 27,
        "srcRank": 28,
        "query": "hoosier lottery technical issue",
        "category": "business",
        "heat": 63,
        "url": "https://www.google.com/search?q=hoosier%20lottery%20technical%20issue"
      },
      {
        "rank": 28,
        "srcRank": 29,
        "query": "taylor parker",
        "category": "news",
        "heat": 62,
        "url": "https://www.google.com/search?q=taylor%20parker"
      },
      {
        "rank": 29,
        "srcRank": 30,
        "query": "james harden",
        "category": "sports",
        "heat": 61,
        "url": "https://www.google.com/search?q=james%20harden"
      },
      {
        "rank": 30,
        "srcRank": 31,
        "query": "gene shalit",
        "category": "entertainment",
        "heat": 59,
        "url": "https://www.google.com/search?q=gene%20shalit"
      },
      {
        "rank": 31,
        "srcRank": 32,
        "query": "mexico world cup",
        "category": "sports",
        "heat": 58,
        "url": "https://www.google.com/search?q=mexico%20world%20cup"
      },
      {
        "rank": 32,
        "srcRank": 33,
        "query": "david hockney",
        "category": "entertainment",
        "heat": 56,
        "url": "https://www.google.com/search?q=david%20hockney"
      },
      {
        "rank": 33,
        "srcRank": 34,
        "query": "nancy guthrie",
        "category": "news",
        "heat": 55,
        "url": "https://www.google.com/search?q=nancy%20guthrie"
      },
      {
        "rank": 34,
        "srcRank": 35,
        "query": "kennedy center",
        "category": "news",
        "heat": 54,
        "url": "https://www.google.com/search?q=kennedy%20center"
      },
      {
        "rank": 35,
        "srcRank": 36,
        "query": "us-iran",
        "category": "news",
        "heat": 52,
        "url": "https://www.google.com/search?q=us-iran"
      },
      {
        "rank": 36,
        "srcRank": 37,
        "query": "fda farm rich pizza recall",
        "category": "business",
        "heat": 51,
        "url": "https://www.google.com/search?q=fda%20farm%20rich%20pizza%20recall"
      },
      {
        "rank": 37,
        "srcRank": 38,
        "query": "mariska hargitay",
        "category": "entertainment",
        "heat": 49,
        "url": "https://www.google.com/search?q=mariska%20hargitay"
      },
      {
        "rank": 38,
        "srcRank": 39,
        "query": "midland texas",
        "category": "news",
        "heat": 48,
        "url": "https://www.google.com/search?q=midland%20texas"
      },
      {
        "rank": 39,
        "srcRank": 40,
        "query": "katy perry",
        "category": "music",
        "heat": 46,
        "url": "https://www.google.com/search?q=katy%20perry"
      },
      {
        "rank": 40,
        "srcRank": 41,
        "query": "elle",
        "category": "entertainment",
        "heat": 45,
        "url": "https://www.google.com/search?q=elle"
      },
      {
        "rank": 41,
        "srcRank": 42,
        "query": "belfast",
        "category": "news",
        "heat": 44,
        "url": "https://www.google.com/search?q=belfast"
      },
      {
        "rank": 42,
        "srcRank": 43,
        "query": "carmelo anthony trial",
        "category": "news",
        "heat": 42,
        "url": "https://www.google.com/search?q=carmelo%20anthony%20trial"
      },
      {
        "rank": 43,
        "srcRank": 44,
        "query": "nancy mace",
        "category": "news",
        "heat": 41,
        "url": "https://www.google.com/search?q=nancy%20mace"
      },
      {
        "rank": 44,
        "srcRank": 45,
        "query": "ocarina of time remake",
        "category": "gaming",
        "heat": 39,
        "url": "https://www.google.com/search?q=ocarina%20of%20time%20remake"
      },
      {
        "rank": 45,
        "srcRank": 46,
        "query": "kingdom hearts 4",
        "category": "gaming",
        "heat": 38,
        "url": "https://www.google.com/search?q=kingdom%20hearts%204"
      },
      {
        "rank": 46,
        "srcRank": 47,
        "query": "fable 5",
        "category": "gaming",
        "heat": 37,
        "url": "https://www.google.com/search?q=fable%205"
      },
      {
        "rank": 47,
        "srcRank": 48,
        "query": "tefi pessoa",
        "category": "entertainment",
        "heat": 35,
        "url": "https://www.google.com/search?q=tefi%20pessoa"
      },
      {
        "rank": 48,
        "srcRank": 49,
        "query": "susan collins",
        "category": "news",
        "heat": 34,
        "url": "https://www.google.com/search?q=susan%20collins"
      },
      {
        "rank": 49,
        "srcRank": 50,
        "query": "kharg island",
        "category": "news",
        "heat": 32,
        "url": "https://www.google.com/search?q=kharg%20island"
      },
      {
        "rank": 50,
        "srcRank": 51,
        "query": "weston higginbotham",
        "category": "news",
        "heat": 31,
        "url": "https://www.google.com/search?q=weston%20higginbotham"
      },
      {
        "rank": 51,
        "srcRank": 53,
        "query": "toledo shooting",
        "category": "news",
        "heat": 30,
        "url": "https://www.google.com/search?q=toledo%20shooting"
      },
      {
        "rank": 52,
        "srcRank": 54,
        "query": "severe thunderstorm watch",
        "category": "news",
        "heat": 28,
        "url": "https://www.google.com/search?q=severe%20thunderstorm%20watch"
      },
      {
        "rank": 53,
        "srcRank": 56,
        "query": "youtube tv",
        "category": "tech",
        "heat": 27,
        "url": "https://www.google.com/search?q=youtube%20tv"
      },
      {
        "rank": 54,
        "srcRank": 57,
        "query": "disney+",
        "category": "tech",
        "heat": 25,
        "url": "https://www.google.com/search?q=disney%2B"
      },
      {
        "rank": 55,
        "srcRank": 58,
        "query": "national park sign restoration order",
        "category": "news",
        "heat": 24,
        "url": "https://www.google.com/search?q=national%20park%20sign%20restoration%20order"
      },
      {
        "rank": 56,
        "srcRank": 59,
        "query": "world cup today",
        "category": "sports",
        "heat": 23,
        "url": "https://www.google.com/search?q=world%20cup%20today"
      },
      {
        "rank": 57,
        "srcRank": 60,
        "query": "bryan rojas ice detention doral",
        "category": "news",
        "heat": 21,
        "url": "https://www.google.com/search?q=bryan%20rojas%20ice%20detention%20doral"
      },
      {
        "rank": 58,
        "srcRank": 61,
        "query": "restaurant chain",
        "category": "business",
        "heat": 20,
        "url": "https://www.google.com/search?q=restaurant%20chain"
      },
      {
        "rank": 59,
        "srcRank": 62,
        "query": "nogales search anonymous tip",
        "category": "news",
        "heat": 18,
        "url": "https://www.google.com/search?q=nogales%20search%20anonymous%20tip"
      },
      {
        "rank": 60,
        "srcRank": 63,
        "query": "bankruptcy",
        "category": "business",
        "heat": 17,
        "url": "https://www.google.com/search?q=bankruptcy"
      },
      {
        "rank": 61,
        "srcRank": 64,
        "query": "jeremy sisto new look",
        "category": "entertainment",
        "heat": 15,
        "url": "https://www.google.com/search?q=jeremy%20sisto%20new%20look"
      },
      {
        "rank": 62,
        "srcRank": 65,
        "query": "shakira",
        "category": "music",
        "heat": 14,
        "url": "https://www.google.com/search?q=shakira"
      },
      {
        "rank": 63,
        "srcRank": 66,
        "query": "bill ritter",
        "category": "entertainment",
        "heat": 13,
        "url": "https://www.google.com/search?q=bill%20ritter"
      },
      {
        "rank": 64,
        "srcRank": 67,
        "query": "raising kanan",
        "category": "gaming",
        "heat": 11,
        "url": "https://www.google.com/search?q=raising%20kanan"
      },
      {
        "rank": 65,
        "srcRank": 68,
        "query": "anti weaponization fund judge ruling",
        "category": "news",
        "heat": 10,
        "url": "https://www.google.com/search?q=anti%20weaponization%20fund%20judge%20ruling"
      },
      {
        "rank": 66,
        "srcRank": 69,
        "query": "dan and shay",
        "category": "music",
        "heat": 8,
        "url": "https://www.google.com/search?q=dan%20and%20shay"
      },
      {
        "rank": 67,
        "srcRank": 70,
        "query": "anthropic fable mythos ban",
        "category": "gaming",
        "heat": 7,
        "url": "https://www.google.com/search?q=anthropic%20fable%20mythos%20ban"
      },
      {
        "rank": 68,
        "srcRank": 71,
        "query": "el nino 2026",
        "category": "news",
        "heat": 6,
        "url": "https://www.google.com/search?q=el%20nino%202026"
      },
      {
        "rank": 69,
        "srcRank": 72,
        "query": "fear",
        "category": "news",
        "heat": 4,
        "url": "https://www.google.com/search?q=fear"
      },
      {
        "rank": 70,
        "srcRank": 73,
        "query": "cash app mobile phone service",
        "category": "tech",
        "heat": 3,
        "url": "https://www.google.com/search?q=cash%20app%20mobile%20phone%20service"
      },
      {
        "rank": 71,
        "srcRank": 75,
        "query": "judge mcconnell dhs immigration ruling",
        "category": "news",
        "heat": 1,
        "url": "https://www.google.com/search?q=judge%20mcconnell%20dhs%20immigration%20ruling"
      }
    ]
  },
  "live": {
    "source": "مشتق من قائمة هاشتاقات تيك توك الرائجة (Trends MCP)",
    "as_of": "2026-05-15T22:01:29.316598+00:00",
    "note_ar": "Trends MCP لا يوفّر feed لـ Popular LIVE الفعلي. هذا القسم مشتق من إشارات حقيقية: هاشتاقات البث المباشر الرائجة، وأكثر الفئات رواجاً (كغرف بث). ترتيب البثوث الفعلي يحتاج TikTok LIVE API.",
    "highlights": [
      {
        "rank": 1,
        "tag": "justgolive",
        "label": "#justgolive",
        "category": "creator",
        "heat": 100,
        "ksa": false,
        "live": true,
        "url": "https://www.tiktok.com/tag/justgolive"
      },
      {
        "rank": 2,
        "tag": "sidehustlelive",
        "label": "#sidehustlelive",
        "category": "business",
        "heat": 99,
        "ksa": false,
        "live": true,
        "url": "https://www.tiktok.com/tag/sidehustlelive"
      }
    ],
    "rooms": [
      {
        "key": "creator",
        "ar": "صنّاع المحتوى",
        "en": "Creators",
        "icon": "✨",
        "color": "#F5D547",
        "count": 8,
        "bestRank": 1,
        "examples": [
          "justgolive",
          "wipwednesday",
          "deenthegreat"
        ]
      },
      {
        "key": "business",
        "ar": "أعمال ومال",
        "en": "Business",
        "icon": "💼",
        "color": "#6FCF97",
        "count": 2,
        "bestRank": 2,
        "examples": [
          "sidehustlelive",
          "usebloomlearntoinvest"
        ]
      },
      {
        "key": "shopping",
        "ar": "تسوّق",
        "en": "Shopping",
        "icon": "🛍️",
        "color": "#FF8A5C",
        "count": 3,
        "bestRank": 3,
        "examples": [
          "tiktokshopmemorialday",
          "tiktokshopdealsforyou",
          "multicolorcasualset"
        ]
      },
      {
        "key": "sports",
        "ar": "رياضة",
        "en": "Sports",
        "icon": "⚽",
        "color": "#25F4EE",
        "count": 11,
        "bestRank": 4,
        "examples": [
          "worldcup",
          "footbal",
          "boxen"
        ]
      },
      {
        "key": "entertainment",
        "ar": "ترفيه",
        "en": "Entertainment",
        "icon": "🎬",
        "color": "#A66BFF",
        "count": 17,
        "bestRank": 5,
        "examples": [
          "iceman",
          "primevideo",
          "georgieandmandy"
        ]
      },
      {
        "key": "music",
        "ar": "موسيقى",
        "en": "Music",
        "icon": "🎵",
        "color": "#FE2C55",
        "count": 8,
        "bestRank": 7,
        "examples": [
          "dontoliver",
          "edclasvegas",
          "niallhoran"
        ]
      },
      {
        "key": "lifestyle",
        "ar": "لايف ستايل",
        "en": "Lifestyle",
        "icon": "🌿",
        "color": "#7CE0C3",
        "count": 8,
        "bestRank": 11,
        "examples": [
          "memorialday",
          "wednesdayvibes",
          "vidaderancho"
        ]
      },
      {
        "key": "beauty",
        "ar": "جمال",
        "en": "Beauty",
        "icon": "💄",
        "color": "#FF6FB5",
        "count": 2,
        "bestRank": 14,
        "examples": [
          "jamescharles",
          "jamescharlesdrama"
        ]
      },
      {
        "key": "gaming",
        "ar": "ألعاب",
        "en": "Gaming",
        "icon": "🎮",
        "color": "#5B8CFF",
        "count": 6,
        "bestRank": 29,
        "examples": [
          "devilmaycry",
          "octane",
          "dmc"
        ]
      }
    ]
  }
};
